// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWr4Yme3_wAK0YAk--ekAQf6VDjRG_k0U',
    appId: '1:859913008310:web:3d4510adb6e9d46fc8a217',
    messagingSenderId: '859913008310',
    projectId: 'twendebus-app',
    authDomain: 'twendebus-app.firebaseapp.com',
    storageBucket: 'twendebus-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9YAAyHAZASYmgn5u0E8Y0Urb7302rJ5s',
    appId: '1:859913008310:android:501c80fdd963dd53c8a217',
    messagingSenderId: '859913008310',
    projectId: 'twendebus-app',
    storageBucket: 'twendebus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg9fgjEdJbeKcBMjtyjhgvar0R1f_gct8',
    appId: '1:859913008310:ios:6fe144d104f06302c8a217',
    messagingSenderId: '859913008310',
    projectId: 'twendebus-app',
    storageBucket: 'twendebus-app.firebasestorage.app',
    iosBundleId: 'com.example.twendebus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg9fgjEdJbeKcBMjtyjhgvar0R1f_gct8',
    appId: '1:859913008310:ios:6fe144d104f06302c8a217',
    messagingSenderId: '859913008310',
    projectId: 'twendebus-app',
    storageBucket: 'twendebus-app.firebasestorage.app',
    iosBundleId: 'com.example.twendebus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWr4Yme3_wAK0YAk--ekAQf6VDjRG_k0U',
    appId: '1:859913008310:web:901cbcd667dfd338c8a217',
    messagingSenderId: '859913008310',
    projectId: 'twendebus-app',
    authDomain: 'twendebus-app.firebaseapp.com',
    storageBucket: 'twendebus-app.firebasestorage.app',
  );

}